version: 2.1

jobs:
  # Job to lint the Dockerfile using hadolint
  lint-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          # Pulls the hadolint Docker image and uses it to lint the Dockerfile
          name: Lint Dockerfile
          command: docker pull ghcr.io/hadolint/hadolint < Dockerfile

  # Job to build a Docker image from the Dockerfile, login to a container registry, and push the image
  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          # Builds a Docker image from the Dockerfile in the current directory
          name: Build a Docker image
          command: docker build -t ghcr.io/$DOCKERHUB_USERNAME/karsajobs-ui:latest .
      - run:
          # Logs into the container registry using the specified username and personal access token
          name: Docker login to container registry
          command: echo $CR_PAT | docker login -u $DOCKERHUB_USERNAME --password-stdin ghcr.io
      - run:
          # Pushes the built Docker image to the container registry
          name: Push the Docker image to the container registry
          command: docker push ghcr.io/$DOCKERHUB_USERNAME/karsajobs-ui:latest

workflows:
  version: 2
  # Workflow that includes linting and building jobs
  lint-and-build-karsajobs-ui:
    # Defines a workflow that sequentially executes linting and building jobs
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui          