# Define a Kubernetes Service using API version "v1"
apiVersion: v1

# Specify that the Kubernetes resource being defined is of kind "Service"
kind: Service

# Metadata for the Service, including its name
metadata:
  name: rabbitmq-service

# Specification for the Service, defining its properties
spec:
  # Selector to match Pods that should be associated with this Service
  selector:
    app: rabbitmq

  # Define the ports that the Service will expose
  ports:
    # Define a port named "amqp" for the AMQP protocol
    - name: amqp
      protocol: TCP
      port: 5672        # Port on the Service
      targetPort: 5672  # Port on the selected Pods

    # Define a port named "management" for managing RabbitMQ
    - name: management
      protocol: TCP
      port: 15672       # Port on the Service
      targetPort: 15672 # Port on the selected Pods
