apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - istio-gateway
  http:
  - match:
    - uri:
        exact: /order
    - uri:
        exact: /shipping
  - route:
    - destination:
        host: order-service
        port:
          number: 3000
    - destination:
        host: shipping-service
        port:
          number: 3001